version: "2.2"
services:

  timesheet:
    image: "yassine17/achat:1.0"
    build: ./
    ports:
      - "8089:8089"
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/achat-db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    depends_on:
      - mysql
    volumes:
      - .m2:/root/.m2


  mysql:
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=timesheet-devops-db
    ports:
      - "3307:3306"