version: "2.24.5"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=timesheet_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app-timesheet:
    depends_on:
      - mysqldb
    image: mouradhassini/timesheet-devops:1.0.0
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{"spring.datasource.url":"jdbc:mysql://mysqldb:3306/timesheet_db?createDatabaseIfNotExist=true","spring.datasource.username":"root","spring.datasource.password":null,"spring.jpa.properties.hibernate.dialect":"org.hibernate.dialect.MySQL5InnoDBDialect","spring.jpa.hibernate.ddl-auto":"update"}'
    stdin_open: true
    tty: true

volumes:
  db:
